const translations = {
    no: {
        dir: "ltr",
        title: "StreamIP – IPTV-spiller",
        subtitle: "StreamIP er en moderne mediespiller for dine egne IPTV-spillelister og kompatible strømmetjenester. Se direktesendt TV, filmer og TV-serier i et rent og brukervennlig grensesnitt designet for telefoner, nettbrett og Google TV-enheter.",
        description: "StreamIP støtter kompatibel serverpålogging og M3U-spilleliste-URL-er, inkludert avspilling av kompatible HLS/M3U8-strømmer levert gjennom din egen innholdskilde. Når det støttes av leverandøren din, kan serverpålogging profesjonelt organisere direktesendte TV-kanaler, filmer og TV-serier.",
        langSupport: "StreamIP er tilgjengelig på 6 språk: engelsk, norsk, fransk, spansk, portugisisk og arabisk.",
        priceTag: "Kun 40 kr – Engangskjøp (Ingen abonnementskostnader)",
        featuresTitle: "Funksjoner",
        importantTitle: "Viktig informasjon",
        ctaBtn: "Last ned på Google Play",
        footerText: "Ta med ditt eget innhold. Strøm det på din måte med StreamIP.",
        features: [
            "Spill av direktesendte TV-kanaler fra din egen innholdskilde",
            "Bla gjennom filmer og TV-serier i organiserte kategorier",
            "Støtte for kompatibel serverpålogging og M3U-spilleliste-URL-er",
            "Avspillingsstøtte for kompatible HLS/M3U8-strømmer",
            "Støtte for elektronisk programguide (EPG) når tilgjengelig fra kilden din",
            "Cast kompatible strømmer til støttede Google Cast-enheter",
            "Åpne strømmer i en kompatibel ekstern mediespiller",
            "Favoritter for rask tilgang til foretrukket innhold",
            "Nylig spilt og Fortsett å se-seksjoner",
            "Gjenoppta avspilling for filmer og TV-episoder",
            "Alternativer for avspilling av neste episode for støttede serier",
            "Søk og kategorisøk",
            "Støtte for undertekster når tilgjengelig i strømmen",
            "Støtte for telefoner, nettbrett og Google TV-enheter",
            "Sorter innhold etter foretrukket region (øst/vest)",
            "Valgfri applås for ekstra personvern",
            "Alternativer for lyst og mørkt utseende"
        ],
        disclaimers: [
            "StreamIP er kun en mediespiller. Appen tilbyr, selger eller inkluderer ikke TV-kanaler, filmer, TV-serier, spillelister, abonnementer eller strømmekontoer.",
            "For å bruke appen må du legge til din egen kompatible spilleliste eller kontodetaljer fra en tjeneste eller kilde du er autorisert til å bruke.",
            "Du er ansvarlig for å sørge for at du har de nødvendige rettighetene og tillatelsene til å få tilgang til og se innhold som legges til i appen. StreamIP er ikke tilknyttet, godkjent av eller koblet til noen innholdsleverandør.",
            "Tilgjengelig innhold, kategorier, EPG-informasjon, undertekster, avspillingskvalitet, Cast-kompatibilitet og strømmekompatibilitet avhenger av din egen innholdskilde, internettforbindelse og enhetsfunksjoner. Ekstern avspilling krever at en kompatibel mediespillerapp er installert på enheten din."
        ]
    },
    en: {
        dir: "ltr",
        title: "StreamIP – IPTV Player",
        subtitle: "StreamIP is a modern media player for your own IPTV playlists and compatible streaming services. Watch live TV, movies, and TV series in a clean and user-friendly interface designed for phones, tablets, and Google TV devices.",
        description: "StreamIP supports compatible server login and M3U playlist URLs, including playback of compatible HLS/M3U8 streams provided through your own content source. When supported by your provider, server login can offer enhanced organization of live TV channels, movies, and TV series.",
        langSupport: "StreamIP is available in 6 languages: English, Norwegian, French, Spanish, Portuguese, and Arabic.",
        priceTag: "Only €3.99 / $3.99 – One-time purchase (No recurring fees)",
        featuresTitle: "Features",
        importantTitle: "Important Information",
        ctaBtn: "Download on Google Play",
        footerText: "Bring your own content. Stream it your way with StreamIP.",
        features: [
            "Play live TV channels from your own content source",
            "Browse movies and TV series in organized categories",
            "Support for compatible server login and M3U playlist URLs",
            "Playback support for compatible HLS/M3U8 streams",
            "Support for Electronic Program Guide (EPG) when available from your source",
            "Cast compatible streams to supported Google Cast devices",
            "Open streams in a compatible external media player",
            "Favorites for quick access to preferred content",
            "Recently played and Continue Watching sections",
            "Resume playback for movies and TV episodes",
            "Next episode playback options for supported series",
            "Search and category search",
            "Subtitle support when available in the stream",
            "Support for phones, tablets, and Google TV devices",
            "Sort content by preferred region (East/West)",
            "Optional app lock for extra privacy",
            "Light and dark appearance options"
        ],
        disclaimers: [
            "StreamIP is a media player only. The app does not offer, sell, or include any TV channels, movies, TV series, playlists, subscriptions, or streaming accounts.",
            "To use the app, you must add your own compatible playlist or account details from a service or source you are authorized to use.",
            "You are responsible for ensuring you have the necessary rights and permissions to access and view content added to the app. StreamIP is not affiliated with, endorsed by, or connected to any content provider.",
            "Available content, categories, EPG information, subtitles, playback quality, Cast compatibility, and stream compatibility depend on your own content source, internet connection, and device capabilities. External playback requires a compatible media player app to be installed on your device."
        ]
    },
    fr: {
        dir: "ltr",
        title: "StreamIP – Lecteur IPTV",
        subtitle: "StreamIP est un lecteur multimédia moderne pour vos propres listes de lecture IPTV et services de streaming compatibles. Regardez la télévision en direct, des films et des séries télévisées dans une interface épurée et conviviale conçue pour les téléphones, les tablettes et les appareils Google TV.",
        description: "StreamIP prend en charge la connexion au serveur compatible et les URL de liste de lecture M3U, y compris la lecture des flux HLS/M3U8 compatibles fournis par votre propre source de contenu. Lorsque votre fournisseur le prend en charge, la connexion au serveur peut offrir une organisation améliorée des chaînes de télévision en direct, des films et des séries télévisées.",
        langSupport: "StreamIP est disponible en 6 langues : anglais, norvégien, français, espagnol, portugais et arabe.",
        priceTag: "Seulement 3,99 € – Achat unique (Pas de frais récurrents)",
        featuresTitle: "Caractéristiques",
        importantTitle: "Informations Importantes",
        ctaBtn: "Télécharger sur Google Play",
        footerText: "Apportez votre propre contenu. Diffusez-le à votre façon avec StreamIP.",
        features: [
            "Lisez les chaînes de télévision en direct de votre propre source de contenu",
            "Parcourir les films et les séries télévisées dans des catégories organisées",
            "Prise en charge de la connexion au serveur compatible et des URL de liste de lecture M3U",
            "Prise en charge de la lecture des flux HLS/M3U8 compatibles",
            "Prise en charge du Guide Électronique des Programmes (EPG) si disponible auprès de votre source",
            "Diffusez des flux compatibles vers des appareils Google Cast pris en charge",
            "Oouvrir les flux dans un lecteur multimédia externe compatible",
            "Favoris pour un accès rapide au contenu préféré",
            "Sections Joués récemment et Continuer à regarder",
            "Reprendre la lecture des films et des épisodes télévisés",
            "Options de lecture de l'épisode suivant pour les séries prises en charge",
            "Recherche et recherche par catégorie",
            "Prise en charge des sous-titres lorsqu'ils sont disponibles dans le flux",
            "Prise en charge des téléphones, tablettes et appareils Google TV",
            "Trier le contenu par région préférée (Est/Ouest)",
            "Verrouillage optionnel de l'application pour plus de confidentialité",
            "Options d'apparence claire et sombre"
        ],
        disclaimers: [
            "StreamIP est uniquement un lecteur multimédia. L'application ne propose, ne vend ni n'inclut de chaînes de télévision, de films, de séries télévisées, de listes de lecture, d'abonnements ou de comptes de streaming.",
            "Pour utiliser l'application, vous devez ajouter vos propres listes de lecture compatibles ou les détails de votre compte à partir d'un service ou d'une source que vous êtes autorisé à utiliser.",
            "Vous êtes responsable de vous assurer que vous disposez des droits et autorisations nécessaires pour accéder et afficher le contenu ajouté à l'application. StreamIP n'est pas affilié, approuvé ou connecté à un fournisseur de contenu.",
            "Le contenu disponible, les catégories, les informations EPG, les sous-titres, la qualité de lecture, la compatibilité Cast et la compatibilité du flux dépendent de votre propre source de contenu, de votre connexion Internet et des capacités de votre appareil. La lecture externe nécessite qu'une application de lecteur multimédia compatible soit installée sur votre appareil."
        ]
    },
    es: {
        dir: "ltr",
        title: "StreamIP – Reproductor IPTV",
        subtitle: "StreamIP es un reproductor de medios moderno para sus propias listas de reproducción IPTV y servicios de streaming compatibles. Vea televisión en vivo, películas y series de TV en una interfaz limpia y fácil de usar diseñada para teléfonos, tabletas y dispositivos Google TV.",
        description: "StreamIP admite el inicio de sesión de servidor compatible y las URL de listas de reproducción M3U, incluida la reproducción de transmisiones HLS/M3U8 compatibles proporcionadas a través de su propia fuente de contenido. Cuando su proveedor lo admita, el inicio de sesión del servidor puede ofrecer una organización mejorada de canales de televisión en vivo, películas y series de televisión.",
        langSupport: "StreamIP está disponible en 6 idiomas: inglés, noruego, francés, español, portugués y árabe.",
        priceTag: "Solo €3.99 / $3.99 – Pago único (Sin tarifas recurrentes)",
        featuresTitle: "Características",
        importantTitle: "Información Importante",
        ctaBtn: "Descargar en Google Play",
        footerText: "Traiga su propio contenido. Transmítalo a su manera con StreamIP.",
        features: [
            "Reproduzca canales de televisión en vivo desde su propia fuente de contenido",
            "Explore películas y series de televisión en categorías organizadas",
            "Soporte para inicio de sesión de servidor compatible y URL de listas de reproducción M3U",
            "Soporte de reproducción para transmisiones HLS/M3U8 compatibles",
            "Soporte para guía electrónica de programas (EPG) cuando esté disponible desde su fuente",
            "Transmita transmisiones compatibles a dispositivos Google Cast compatibles",
            "Abra transmisiones en un reproductor de medios externo compatible",
            "Favoritos para un acceso rápido al contenido preferido",
            "Secciones de Reproducido recientemente y Continuar viendo",
            "Reanudar la reproducción de películas y episodios de televisión",
            "Opciones de reproducción del próximo episodio para series compatibles",
            "Búsqueda y búsqueda por categorías",
            "Soporte de subtítulos cuando esté disponible en la transmisión",
            "Soporte para teléfonos, tabletas y dispositivos Google TV",
            "Ordene el contenido por región preferida (Este/Oeste)",
            "Bloqueo de aplicación opcional para mayor privacidad",
            "Opciones de apariencia clara y oscura"
        ],
        disclaimers: [
            "StreamIP es solo un reproductor de medios. La aplicación no ofrece, vende ni incluye canales de televisión, películas, series de televisión, listas de reproducción, suscripciones ni cuentas de streaming.",
            "Para usar la aplicación, debe agregar su propia lista de reproducción compatible o los detalles de la cuenta de un servicio o fuente que esté autorizado a usar.",
            "Usted es responsable de asegurarse de tener los derechos y permisos necesarios para acceder y ver el contenido agregado a la aplicación. StreamIP no está afiliado, respaldado ni conectado con ningún proveedor de contenido.",
            "El contenido disponible, las categorías, la información de la EPG, los subtítulos, la calidad de reproducción, la compatibilidad con Cast y la compatibilidad con la transmisión dependen de su propia fuente de contenido, conexión a Internet y capacidades del dispositivo. La reproducción externa requiere que haya una aplicación de reproductor de medios compatible instalada en su dispositivo."
        ]
    },
    pt: {
        dir: "ltr",
        title: "StreamIP – Reprodutor IPTV",
        subtitle: "StreamIP é um reprodutor de mídia moderno para suas próprias listas de reprodução IPTV e serviços de streaming compatíveis. Assista à TV ao vivo, filmes e séries de TV em uma interface limpa e amigável projetada para telefones, tablets e dispositivos Google TV.",
        description: "O StreamIP suporta login de servidor compatível e URLs de lista de reprodução M3U, incluindo a reprodução de fluxos HLS/M3U8 compatíveis fornecidos por meio de sua própria fonte de conteúdo. Quando suportado pelo seu provedor, o login do servidor pode oferecer uma organização aprimorada de canais de TV ao vivo, filmes e séries de TV.",
        langSupport: "O StreamIP está disponível em 6 idiomas: inglês, norueguês, francês, espanhol, português e árabe.",
        priceTag: "Apenas R$ 19,99 / €3.99 – Compra única (Sem assinaturas)",
        featuresTitle: "Recursos",
        importantTitle: "Informações Importantes",
        ctaBtn: "Baixar no Google Play",
        footerText: "Traga seu próprio conteúdo. Transmita do seu jeito com o StreamIP.",
        features: [
            "Reproduza canais de TV ao vivo de sua própria fonte de conteúdo",
            "Navegue por filmes e séries de TV em categorias organizadas",
            "Suporte para login de servidor compatível e URLs de lista de reprodução M3U",
            "Suporte de reprodução para fluxos HLS/M3U8 compatíveis",
            "Suporte para Guia Eletrônico de Programação (EPG) quando disponível na sua fonte",
            "Transmita fluxos compatíveis para dispositivos Google Cast suportados",
            "Abra fluxos em um reprodutor de mídia externo compatível",
            "Favoritos para acesso rápido ao conteúdo preferido",
            "Seções Reproduzidos recentemente e Continuar assistindo",
            "Retomar a reprodução de filmes e episódios de TV",
            "Opções de reprodução do próximo episódio para séries suportadas",
            "Busca e busca por categoria",
            "Suporte a legendas quando disponível no fluxo",
            "Suporte para telefones, tablets e dispositivos Google TV",
            "Classifique o conteúdo por região preferida (Leste/Oeste)",
            "Bloqueio de aplicativo opcional para privacidade extra",
            "Opções de aparência clara e escura"
        ],
        disclaimers: [
            "O StreamIP é apenas um reprodutor de mídia. O aplicativo não oferece, vende ou inclui canais de TV, filmes, séries de TV, listas de reprodução, assinaturas ou contas de streaming.",
            "Para usar o aplicativo, você deve adicionar sua própria lista de reprodução compatível ou detalhes da conta de um serviço ou fonte que você está autorizado a usar.",
            "Você é responsável por garantir que possui os direitos e permissões necessários para acessar e visualizar o conteúdo adicionado ao aplicativo. O StreamIP não é afiliado, endossado ou conectado a nenhum provedor de conteúdo.",
            "O conteúdo disponível, categorias, informações de EPG, legendas, qualidade de reprodução, compatibilidade com Cast e compatibilidade de fluxo dependem de sua própria fonte de conteúdo, conexão com a Internet e recursos do dispositivo. A reprodução externa requer que um aplicativo reprodutor de mídia compatível esteja instalado no seu dispositivo."
        ]
    },
    ar: {
        dir: "rtl",
        title: "StreamIP – مشغل IPTV",
        subtitle: "StreamIP هو مشغل وسائط حديث لقوائم تشغيل IPTV الخاصة بك وخدمات البث المتوافقة. شاهد البث المباشر للقنوات التلفزيونية والأفلام والمسلسلات في واجهة نظيفة وسهلة الاستخدام مصممة للهواتف والأجهزة اللوحية وأجهزة Google TV.",
        description: "يدعم StreamIP تسجيل الدخول المتوافق مع الخادم وعناوين URL لقوائم تشغيل M3U، بما في ذلك تشغيل تدفقات HLS/M3U8 المتوافقة المقدمة من مصدر المحتوى الخاص بك. عندما يكون مدعومًا من مزود الخدمة الخاص بك، يمكن لتسجيل الدخول إلى الخادم توفير تنظيم محسن للقنوات التلفزيونية المباشرة والأفلام والمسلسلات التلفزيونية.",
        langSupport: "يتوفر StreamIP بـ 6 لغات: الإنجليزية والنرويجية والفرنسية والإسبانية والبرتغالية والعربية.",
        priceTag: "3.99 دولار فقط - شراء لمرة واحدة (بدون رسوم متكررة)",
        featuresTitle: "الميزات",
        importantTitle: "معلومات هامة",
        ctaBtn: "تحميل من Google Play",
        footerText: "أحضر المحتوى الخاص بك. ابدأ البث بطريقتك مع StreamIP.",
        features: [
            "تشغيل قنوات التلفزيon المباشرة من مصدر المحتوى الخاص بك",
            "تصفح الأفلام والمسلسلات التلفزيونية في فئات منظمة",
            "دعم تسجيل الدخول المتوافق مع الخادم وعناوين URL لقوائم تشغيل M3U",
            "دعم تشغيل تدفقات HLS/M3U8 المتوافقة",
            "دعم دليل البرامج الإلكتروني (EPG) عند توفره من مصدرك",
            "بث التدفقات المتوافقة إلى أجهزة Google Cast المدعومة",
            "فتح التدفقات في مشغل وسائط خارجي متوافق",
            "المفضلة للوصول السريع إلى المحتوى المفضل",
            "أقسام المشغلة مؤخرًا ومتابعة المشاهدة",
            "استئناف التشغيل للأفلام وحلقات التلفزيون",
            "خيارات تشغيل الحلقة التالية للمسلسلات المدعومة",
            "البحث والبحث في الفئات",
            "دعم الترجمة المصاحبة عند توفرها في البث",
            "دعم الهواتف والأجهزة اللوحية وأجهزة Google TV",
            "فرز المحتوى حسب المنطقة المفضلة (الشرق/الغرب)",
            "قفل تطبيق اختياري لمزيد من الخصوصية",
            "خيارات المظهر الفاتح والداكن"
        ],
        disclaimers: [
            "برنامج StreamIP هو مجرد مشغل وسائط فقط. لا يوفر التطبيق أو يبيع أو يتضمن أي قنوات تلفزيونية أو أفلام أو مسلسلات تلفزيونية أو قوائم تشغيل أو اشتراكات أو حسابات بث.",
            "لاستخدام التطبيق، يجب عليك إضافة قائمة التشغيل المتوافقة الخاصة بك أو تفاصيل الحساب من خدمة أو مصدر مصرح لك باستخدامه.",
            "أنت مسؤول عن ضمان حصولك على الحقوق والأذونات اللازمة للوصول إلى المحتوى المضاف إلى التطبيق وعرضه. لا ينتمي StreamIP إلى أي مزود محتوى ولا يعتمده أو يرتبط به.",
            "يعتمد المحتوى المتاح والفئات ومعلومات EPG والترجمات وجودة التشغيل وتوافق البث (Cast) وتوافق التدفق على مصدر المحتوى الخاص بك واتصال الإنترنت وميزات جهازك. يتطلب التشغيل الخارجي تثبيت تطبيق مشغل وسائط متوافق على جهازك."
        ]
    }
};