const translations = {
    no: {
        dir: "ltr",
        title: "StreamIP – IPTV-spiller",
        subtitle: "StreamIP er en moderne mediespiller for dine egne IPTV-spillelister og kompatible strømmetjenester. Se direktesendt TV, filmer og TV-serier i et rent og brukervennlig grensesnitt designet for telefoner, nettbrett og Google TV-enheter.",
        description: "StreamIP støtter kompatibel serverpålogging og M3U-spilleliste-URL-er, inkludert avspilling av kompatible HLS/M3U8-strømmer levert gjennom din egen innholdskilde. Når det støttes av leverandøren din, kan serverpålogging profesjonelt organisere direktesendte TV-kanaler, filmer og TV-serier.",
        langSupport: "StreamIP er tilgjengelig på 9 språk: engelsk, norsk, fransk, spansk, portugisisk, arabisk, tysk, italiensk og polsk.",
        priceTag: "Kun 40 kr – Engangskjøp (Ingen abonnementskostnader)",
        featuresTitle: "Funksjoner",
        importantTitle: "Viktig informasjon",
        ctaBtn: "Last ned på Google Play",
        footerText: "Ta med ditt eget innhold. Strøm det på din måte med StreamIP.",
        features: [
            "Spill av direktesendte TV-kanaler fra din egen innholdskilde",
            "Bla gjennom filmer og TV-serier i organiserte kategorier",
            "Støtte for kompatibel serverpålogging og M3U-spilleliste-URL-er",
            "Avspillingsstøtte for kompatible HLS/M3U8-strømmer",
            "Støtte for elektronisk programguide (EPG) når tilgjengelig fra kilden din",
            "Cast kompatible strømmer til støttede Google Cast-enheter",
            "Åpne strømmer i en kompatibel ekstern mediespiller",
            "Favoritter for rask tilgang til foretrukket innhold",
            "Nylig spilt og Fortsett å se-seksjoner",
            "Gjenoppta avspilling for filmer og TV-episoder",
            "Alternativer for avspilling av neste episode for støttede serier",
            "Søk og kategorisøk",
            "Støtte for undertekster når tilgjengelig i strømmen",
            "Støtte for telefoner, nettbrett og Google TV-enheter",
            "Sorter innhold etter foretrukket region (øst/vest)",
            "Valgfri applås for ekstra personvern",
            "Alternativer for lyst og mørkt utseende"
        ],
        disclaimers: [
            "StreamIP er kun en mediespiller. Appen tilbyr, selger eller inkluderer ikke TV-kanaler, filmer, TV-serier, spillelister, abonnementer eller strømmekontoer.",
            "For å bruke appen må du legge til din egen kompatible spilleliste eller kontodetaljer fra en tjeneste eller kilde du er autorisert til å bruke.",
            "Du er ansvarlig for å sørge for at du har de nødvendige rettighetene og tillatelsene til å få tilgang til og se innhold som legges til i appen. StreamIP er ikke tilknyttet, godkjent av eller koblet til noen innholdsleverandør.",
            "Tilgjengelig innhold, kategorier, EPG-informasjon, undertekster, avspillingskvalitet, Cast-kompatibilitet og strømmekompatibilitet avhenger av din egen innholdskilde, internettforbindelse og enhetsfunksjoner. Ekstern avspilling krever at en kompatibel mediespillerapp er installert på enheten din."
        ]
    },
    en: {
        dir: "ltr",
        title: "StreamIP – IPTV Player",
        subtitle: "StreamIP is a modern media player for your own IPTV playlists and compatible streaming services. Watch live TV, movies, and TV series in a clean and user-friendly interface designed for phones, tablets, and Google TV devices.",
        description: "StreamIP supports compatible server login and M3U playlist URLs, including playback of compatible HLS/M3U8 streams provided through your own content source. When supported by your provider, server login can offer enhanced organization of live TV channels, movies, and TV series.",
        langSupport: "StreamIP is available in 9 languages: English, Norwegian, French, Spanish, Portuguese, Arabic, German, Italian, and Polish.",
        priceTag: "Only €3.99 / $3.99 – One-time purchase (No recurring fees)",
        featuresTitle: "Features",
        importantTitle: "Important Information",
        ctaBtn: "Download on Google Play",
        footerText: "Bring your own content. Stream it your way with StreamIP.",
        features: [
            "Play live TV channels from your own content source",
            "Browse movies and TV series in organized categories",
            "Support for compatible server login and M3U playlist URLs",
            "Playback support for compatible HLS/M3U8 streams",
            "Support for Electronic Program Guide (EPG) when available from your source",
            "Cast compatible streams to supported Google Cast devices",
            "Open streams in a compatible external media player",
            "Favorites for quick access to preferred content",
            "Recently played and Continue Watching sections",
            "Resume playback for movies and TV episodes",
            "Next episode playback options for supported series",
            "Search and category search",
            "Subtitle support when available in the stream",
            "Support for phones, tablets, and Google TV devices",
            "Sort content by preferred region (East/West)",
            "Optional app lock for extra privacy",
            "Light and dark appearance options"
        ],
        disclaimers: [
            "StreamIP is a media player only. The app does not offer, sell, or include any TV channels, movies, TV series, playlists, subscriptions, or streaming accounts.",
            "To use the app, you must add your own compatible playlist or account details from a service or source you are authorized to use.",
            "You are responsible for ensuring you have the necessary rights and permissions to access and view content added to the app. StreamIP is not affiliated with, endorsed by, or connected to any content provider.",
            "Available content, categories, EPG information, subtitles, playback quality, Cast compatibility, and stream compatibility depend on your own content source, internet connection, and device capabilities. External playback requires a compatible media player app to be installed on your device."
        ]
    },
    fr: {
        dir: "ltr",
        title: "StreamIP – Lecteur IPTV",
        subtitle: "StreamIP est un lecteur multimédia moderne pour vos propres listes de lecture IPTV et services de streaming compatibles. Regardez la télévision en direct, des films et des séries télévisées dans une interface épurée et conviviale conçue pour les téléphones, les tablettes et les appareils Google TV.",
        description: "StreamIP prend en charge la connexion au serveur compatible et les URL de liste de lecture M3U, y compris la lecture des flux HLS/M3U8 compatibles fournis par votre propre source de contenu. Lorsque votre fournisseur le prend en charge, la connexion au serveur peut offrir une organisation améliorée des chaînes de télévision en direct, des films et des séries télévisées.",
        langSupport: "StreamIP est disponible en 9 langues : anglais, norvégien, français, espagnol, portugais, arabe, allemand, italien et polonais.",
        priceTag: "Seulement 3,99 € – Achat unique (Pas de frais récurrents)",
        featuresTitle: "Caractéristiques",
        importantTitle: "Informations Importantes",
        ctaBtn: "Télécharger sur Google Play",
        footerText: "Apportez votre propre contenu. Diffusez-le à votre façon avec StreamIP.",
        features: [
            "Lisez les chaînes de télévision en direct de votre propre source de contenu",
            "Parcourir les films et les séries télévisées dans des catégories organisées",
            "Prise en charge de la connexion au serveur compatible et des URL de liste de lecture M3U",
            "Prise en charge de la lecture des flux HLS/M3U8 compatibles",
            "Prise en charge du Guide Électronique des Programmes (EPG) si disponible auprès de votre source",
            "Diffusez des flux compatibles vers des appareils Google Cast pris en charge",
            "Oouvrir les flux dans un lecteur multimédia externe compatible",
            "Favoris pour un accès rapide au contenu préféré",
            "Sections Joués récemment et Continuer à regarder",
            "Reprendre la lecture des films et des épisodes télévisés",
            "Options de lecture de l'épisode suivant pour les séries prises en charge",
            "Recherche et recherche par catégorie",
            "Prise en charge des sous-titres lorsqu'ils sont disponibles dans le flux",
            "Prise en charge des téléphones, tablettes et appareils Google TV",
            "Trier le contenu par région préférée (Est/Ouest)",
            "Verrouillage optionnel de l'application pour plus de confidentialité",
            "Options d'apparence claire et sombre"
        ],
        disclaimers: [
            "StreamIP est uniquement un lecteur multimédia. L'application ne propose, ne vend ni n'inclut de chaînes de télévision, de films, de séries télévisées, de listes de lecture, d'abonnements ou de comptes de streaming.",
            "Pour utiliser l'application, vous devez ajouter vos propres listes de lecture compatibles ou les détails de votre compte à partir d'un service ou d'une source que vous êtes autorisé à utiliser.",
            "Vous êtes responsable de vous assurer que vous disposez des droits et autorisations nécessaires pour accéder et afficher le contenu ajouté à l'application. StreamIP n'est pas affilié, approuvé ou connecté à un fournisseur de contenu.",
            "Le contenu disponible, les catégories, les informations EPG, les sous-titres, la qualité de lecture, la compatibilité Cast et la compatibilité du flux dépendent de votre propre source de contenu, de votre connexion Internet et des capacités de votre appareil. La lecture externe nécessite qu'une application de lecteur multimédia compatible soit installée sur votre appareil."
        ]
    },
    es: {
        dir: "ltr",
        title: "StreamIP – Reproductor IPTV",
        subtitle: "StreamIP es un reproductor de medios moderno para sus propias listas de reproducción IPTV y servicios de streaming compatibles. Vea televisión en vivo, películas y series de TV en una interfaz limpia y fácil de usar diseñada para teléfonos, tabletas y dispositivos Google TV.",
        description: "StreamIP admite el inicio de sesión de servidor compatible y las URL de listas de reproducción M3U, incluida la reproducción de transmisiones HLS/M3U8 compatibles proporcionadas a través de su propia fuente de contenido. Cuando su proveedor lo admita, el inicio de sesión del servidor puede ofrecer una organización mejorada de canales de televisión en vivo, películas y series de televisión.",
        langSupport: "StreamIP está disponible en 9 idiomas: inglés, noruego, francés, español, portugués, árabe, alemán, italiano y polaco.",
        priceTag: "Solo €3.99 / $3.99 – Pago único (Sin tarifas recurrentes)",
        featuresTitle: "Características",
        importantTitle: "Información Importante",
        ctaBtn: "Descargar en Google Play",
        footerText: "Traiga su propio contenido. Transmítalo a su manera con StreamIP.",
        features: [
            "Reproduzca canales de televisión en vivo desde su propia fuente de contenido",
            "Explore películas y series de televisión en categorías organizadas",
            "Soporte para inicio de sesión de servidor compatible y URL de listas de reproducción M3U",
            "Soporte de reproducción para transmisiones HLS/M3U8 compatibles",
            "Soporte para guía electrónica de programas (EPG) cuando esté disponible desde su fuente",
            "Transmita transmisiones compatibles a dispositivos Google Cast compatibles",
            "Abra transmisiones en un reproductor de medios externo compatible",
            "Favoritos para un acceso rápido al contenido preferido",
            "Secciones de Reproducido recientemente y Continuar viendo",
            "Reanudar la reproducción de películas y episodios de televisión",
            "Opciones de reproducción del próximo episodio para series compatibles",
            "Búsqueda y búsqueda por categorías",
            "Soporte de subtítulos cuando esté disponible en la transmisión",
            "Soporte para teléfonos, tabletas y dispositivos Google TV",
            "Ordene el contenido por región preferida (Este/Oeste)",
            "Bloqueo de aplicación opcional para mayor privacidad",
            "Opciones de apariencia clara y oscura"
        ],
        disclaimers: [
            "StreamIP es solo un reproductor de medios. La aplicación no ofrece, vende ni incluye canales de televisión, películas, series de televisión, listas de reproducción, suscripciones ni cuentas de streaming.",
            "Para usar la aplicación, debe agregar su propia lista de reproducción compatible o los detalles de la cuenta de un servicio o fuente que esté autorizado a usar.",
            "Usted es responsable de asegurarse de tener los derechos y permisos necesarios para acceder y ver el contenido agregado a la aplicación. StreamIP no está afiliado, respaldado ni conectado con ningún proveedor de contenido.",
            "El contenido disponible, las categorías, la información de la EPG, los subtítulos, la calidad de reproducción, la compatibilidad con Cast y la compatibilidad con la transmisión dependen de su propia fuente de contenido, conexión a Internet y capacidades del dispositivo. La reproducción externa requiere que haya una aplicación de reproductor de medios compatible instalada en su dispositivo."
        ]
    },
    pt: {
        dir: "ltr",
        title: "StreamIP – Reprodutor IPTV",
        subtitle: "StreamIP é um reprodutor de mídia moderno para suas próprias listas de reprodução IPTV e serviços de streaming compatíveis. Assista à TV ao vivo, filmes e séries de TV em uma interface limpa e amigável projetada para telefones, tablets e dispositivos Google TV.",
        description: "O StreamIP suporta login de servidor compatível e URLs de lista de reprodução M3U, incluindo a reprodução de fluxos HLS/M3U8 compatíveis fornecidos por meio de sua própria fonte de conteúdo. Quando suportado pelo seu provedor, o login do servidor pode oferecer uma organização aprimorada de canais de TV ao vivo, filmes e séries de TV.",
        langSupport: "O StreamIP está disponível em 9 idiomas: inglês, norueguês, francês, espanhol, português, árabe, alemão, italiano e polonês.",
        priceTag: "Apenas R$ 19,99 / €3.99 – Compra única (Sem assinaturas)",
        featuresTitle: "Recursos",
        importantTitle: "Informações Importantes",
        ctaBtn: "Baixar no Google Play",
        footerText: "Traga seu próprio conteúdo. Transmita do seu jeito com o StreamIP.",
        features: [
            "Reproduza canais de TV ao vivo de sua própria fonte de conteúdo",
            "Navegue por filmes e séries de TV em categorias organizadas",
            "Suporte para login de servidor compatível e URLs de lista de reprodução M3U",
            "Suporte de reprodução para fluxos HLS/M3U8 compatíveis",
            "Suporte para Guia Eletrônico de Programação (EPG) quando disponível na sua fonte",
            "Transmita fluxos compatíveis para dispositivos Google Cast suportados",
            "Abra fluxos em um reprodutor de mídia externo compatível",
            "Favoritos para acesso rápido ao conteúdo preferido",
            "Seções Reproduzidos recentemente e Continuar assistindo",
            "Retomar a reprodução de filmes e episódios de TV",
            "Opções de reprodução do próximo episódio para séries suportadas",
            "Busca e busca por categoria",
            "Suporte a legendas quando disponível no fluxo",
            "Suporte para telefones, tablets e dispositivos Google TV",
            "Classifique o conteúdo por região preferida (Leste/Oeste)",
            "Bloqueio de aplicativo opcional para privacidade extra",
            "Opções de aparência clara e escura"
        ],
        disclaimers: [
            "O StreamIP é apenas um reprodutor de mídia. O aplicativo não oferece, vende ou inclui canais de TV, filmes, séries de TV, listas de reprodução, assinaturas ou contas de streaming.",
            "Para usar o aplicativo, você deve adicionar sua própria lista de reprodução compatível ou detalhes da conta de um serviço ou fonte que você está autorizado a usar.",
            "Você é responsável por garantir que possui os direitos e permissões necessários para acessar e visualizar o conteúdo adicionado ao aplicativo. O StreamIP não é afiliado, endossado ou conectado a nenhum provedor de conteúdo.",
            "O conteúdo disponível, categorias, informações de EPG, legendas, qualidade de reprodução, compatibilidade com Cast e compatibilidade de fluxo dependem de sua própria fonte de conteúdo, conexão com a Internet e recursos do dispositivo. A reprodução externa requer que um aplicativo reprodutor de mídia compatível esteja instalado no seu dispositivo."
        ]
    },
        de: {
        dir: "ltr",
        title: "StreamIP – IPTV-Player",
        subtitle: "StreamIP ist ein moderner Mediaplayer für deine eigenen IPTV-Playlists und kompatible Streaming-Dienste. Sieh Live-TV, Filme und TV-Serien in einer übersichtlichen und benutzerfreundlichen Oberfläche, die für Smartphones, Tablets und Google-TV-Geräte entwickelt wurde.",
        description: "StreamIP unterstützt kompatible Server-Anmeldung und M3U-Playlist-URLs, einschließlich der Wiedergabe kompatibler HLS/M3U8-Streams aus deiner eigenen Inhaltsquelle. Wenn dein Anbieter dies unterstützt, kann die Server-Anmeldung Live-TV-Kanäle, Filme und TV-Serien besser organisieren.",
        langSupport: "StreamIP ist in 9 Sprachen verfügbar: Englisch, Norwegisch, Französisch, Spanisch, Portugiesisch, Arabisch, Deutsch, Italienisch und Polnisch.",
        priceTag: "Nur 3,99 € – Einmaliger Kauf (Keine wiederkehrenden Gebühren)",
        featuresTitle: "Funktionen",
        importantTitle: "Wichtige Informationen",
        ctaBtn: "Bei Google Play herunterladen",
        footerText: "Bring deine eigenen Inhalte mit. Streame sie auf deine Weise mit StreamIP.",
        features: [
            "Live-TV-Kanäle aus deiner eigenen Inhaltsquelle abspielen",
            "Filme und TV-Serien in organisierten Kategorien durchsuchen",
            "Unterstützung für kompatible Server-Anmeldung und M3U-Playlist-URLs",
            "Wiedergabe kompatibler HLS/M3U8-Streams",
            "Unterstützung für elektronische Programmführer (EPG), wenn von deiner Quelle verfügbar",
            "Kompatible Streams an unterstützte Google-Cast-Geräte übertragen",
            "Streams in einem kompatiblen externen Mediaplayer öffnen",
            "Favoriten für schnellen Zugriff auf bevorzugte Inhalte",
            "Bereiche für kürzlich abgespielt und Weiterschauen",
            "Wiedergabe für Filme und TV-Episoden fortsetzen",
            "Optionen für die nächste Episode bei unterstützten Serien",
            "Suche und Kategoriesuche",
            "Unterstützung für Untertitel, wenn im Stream verfügbar",
            "Unterstützung für Smartphones, Tablets und Google-TV-Geräte",
            "Inhalte nach bevorzugter Region sortieren (Ost/West)",
            "Optionale App-Sperre für zusätzlichen Datenschutz",
            "Optionen für helles und dunkles Erscheinungsbild"
        ],
        disclaimers: [
            "StreamIP ist ausschließlich ein Mediaplayer. Die App bietet, verkauft oder enthält keine TV-Kanäle, Filme, TV-Serien, Playlists, Abonnements oder Streaming-Konten.",
            "Um die App zu verwenden, musst du deine eigene kompatible Playlist oder Kontodaten von einem Dienst oder einer Quelle hinzufügen, zu deren Nutzung du berechtigt bist.",
            "Du bist dafür verantwortlich sicherzustellen, dass du die erforderlichen Rechte und Berechtigungen hast, um auf die in der App hinzugefügten Inhalte zuzugreifen und sie anzusehen. StreamIP ist mit keinem Inhaltsanbieter verbunden, wird von keinem unterstützt und steht mit keinem in Verbindung.",
            "Verfügbare Inhalte, Kategorien, EPG-Informationen, Untertitel, Wiedergabequalität, Cast-Kompatibilität und Stream-Kompatibilität hängen von deiner eigenen Inhaltsquelle, Internetverbindung und den Fähigkeiten deines Geräts ab. Externe Wiedergabe erfordert, dass eine kompatible Mediaplayer-App auf deinem Gerät installiert ist."
        ]
    },
    it: {
        dir: "ltr",
        title: "StreamIP – Lettore IPTV",
        subtitle: "StreamIP è un lettore multimediale moderno per le tue playlist IPTV e i servizi di streaming compatibili. Guarda TV in diretta, film e serie TV in un'interfaccia pulita e facile da usare, progettata per telefoni, tablet e dispositivi Google TV.",
        description: "StreamIP supporta l'accesso a server compatibili e gli URL di playlist M3U, inclusa la riproduzione di flussi HLS/M3U8 compatibili forniti tramite la tua fonte di contenuti. Quando supportato dal tuo provider, l'accesso al server può offrire una migliore organizzazione di canali TV in diretta, film e serie TV.",
        langSupport: "StreamIP è disponibile in 9 lingue: inglese, norvegese, francese, spagnolo, portoghese, arabo, tedesco, italiano e polacco.",
        priceTag: "Solo 3,99 € – Acquisto unico (Nessun costo ricorrente)",
        featuresTitle: "Funzionalità",
        importantTitle: "Informazioni Importanti",
        ctaBtn: "Scarica da Google Play",
        footerText: "Porta i tuoi contenuti. Guardali a modo tuo con StreamIP.",
        features: [
            "Riproduci canali TV in diretta dalla tua fonte di contenuti",
            "Sfoglia film e serie TV in categorie organizzate",
            "Supporto per accesso a server compatibili e URL di playlist M3U",
            "Supporto alla riproduzione di flussi HLS/M3U8 compatibili",
            "Supporto alla guida elettronica ai programmi (EPG) quando disponibile dalla tua fonte",
            "Trasmetti flussi compatibili a dispositivi Google Cast supportati",
            "Apri i flussi in un lettore multimediale esterno compatibile",
            "Preferiti per un accesso rapido ai contenuti preferiti",
            "Sezioni Riprodotti di recente e Continua a guardare",
            "Riprendi la riproduzione di film ed episodi TV",
            "Opzioni per l'episodio successivo nelle serie supportate",
            "Ricerca e ricerca per categoria",
            "Supporto ai sottotitoli quando disponibili nel flusso",
            "Supporto per telefoni, tablet e dispositivi Google TV",
            "Ordina i contenuti per regione preferita (Est/Ovest)",
            "Blocco app opzionale per maggiore privacy",
            "Opzioni per aspetto chiaro e scuro"
        ],
        disclaimers: [
            "StreamIP è solo un lettore multimediale. L'app non offre, vende o include canali TV, film, serie TV, playlist, abbonamenti o account di streaming.",
            "Per utilizzare l'app, devi aggiungere la tua playlist compatibile o i dettagli dell'account da un servizio o una fonte che sei autorizzato a utilizzare.",
            "Sei responsabile di assicurarti di avere i diritti e le autorizzazioni necessari per accedere e visualizzare i contenuti aggiunti all'app. StreamIP non è affiliato, approvato o collegato ad alcun fornitore di contenuti.",
            "I contenuti disponibili, le categorie, le informazioni EPG, i sottotitoli, la qualità di riproduzione, la compatibilità Cast e la compatibilità dei flussi dipendono dalla tua fonte di contenuti, dalla connessione Internet e dalle capacità del dispositivo. La riproduzione esterna richiede che sul dispositivo sia installata un'app lettore multimediale compatibile."
        ]
    },
    pl: {
        dir: "ltr",
        title: "StreamIP – Odtwarzacz IPTV",
        subtitle: "StreamIP to nowoczesny odtwarzacz multimedialny dla własnych playlist IPTV i kompatybilnych usług streamingowych. Oglądaj telewizję na żywo, filmy i seriale TV w przejrzystym, łatwym w obsłudze interfejsie zaprojektowanym dla telefonów, tabletów i urządzeń Google TV.",
        description: "StreamIP obsługuje kompatybilne logowanie do serwera oraz adresy URL playlist M3U, w tym odtwarzanie kompatybilnych strumieni HLS/M3U8 dostarczanych przez własne źródło treści. Jeśli Twój dostawca to obsługuje, logowanie do serwera może zapewnić lepszą organizację kanałów TV na żywo, filmów i seriali TV.",
        langSupport: "StreamIP jest dostępny w 9 językach: angielskim, norweskim, francuskim, hiszpańskim, portugalskim, arabskim, niemieckim, włoskim i polskim.",
        priceTag: "Tylko 3,99 € – Jednorazowy zakup (Bez opłat cyklicznych)",
        featuresTitle: "Funkcje",
        importantTitle: "Ważne Informacje",
        ctaBtn: "Pobierz z Google Play",
        footerText: "Dodaj własne treści. Oglądaj je po swojemu ze StreamIP.",
        features: [
            "Odtwarzaj kanały TV na żywo z własnego źródła treści",
            "Przeglądaj filmy i seriale TV w uporządkowanych kategoriach",
            "Obsługa kompatybilnego logowania do serwera i adresów URL playlist M3U",
            "Obsługa odtwarzania kompatybilnych strumieni HLS/M3U8",
            "Obsługa elektronicznego przewodnika po programach (EPG), gdy jest dostępny z Twojego źródła",
            "Przesyłaj kompatybilne strumienie na obsługiwane urządzenia Google Cast",
            "Otwieraj strumienie w kompatybilnym zewnętrznym odtwarzaczu multimedialnym",
            "Ulubione dla szybkiego dostępu do preferowanych treści",
            "Sekcje Ostatnio odtwarzane i Kontynuuj oglądanie",
            "Wznawianie odtwarzania filmów i odcinków TV",
            "Opcje odtwarzania następnego odcinka dla obsługiwanych seriali",
            "Wyszukiwanie i wyszukiwanie według kategorii",
            "Obsługa napisów, gdy są dostępne w strumieniu",
            "Obsługa telefonów, tabletów i urządzeń Google TV",
            "Sortowanie treści według preferowanego regionu (Wschód/Zachód)",
            "Opcjonalna blokada aplikacji dla większej prywatności",
            "Opcje jasnego i ciemnego wyglądu"
        ],
        disclaimers: [
            "StreamIP jest wyłącznie odtwarzaczem multimedialnym. Aplikacja nie oferuje, nie sprzedaje ani nie zawiera żadnych kanałów TV, filmów, seriali TV, playlist, subskrypcji ani kont streamingowych.",
            "Aby korzystać z aplikacji, musisz dodać własną kompatybilną playlistę lub dane konta z usługi albo źródła, z którego masz prawo korzystać.",
            "Użytkownik odpowiada za upewnienie się, że posiada wymagane prawa i uprawnienia do dostępu oraz oglądania treści dodanych do aplikacji. StreamIP nie jest powiązany, wspierany ani połączony z żadnym dostawcą treści.",
            "Dostępne treści, kategorie, informacje EPG, napisy, jakość odtwarzania, kompatybilność Cast i kompatybilność strumieni zależą od własnego źródła treści, połączenia internetowego oraz możliwości urządzenia. Odtwarzanie zewnętrzne wymaga zainstalowania kompatybilnej aplikacji odtwarzacza multimedialnego na urządzeniu."
        ]
    },
    ar: {
        dir: "rtl",
        title: "StreamIP – مشغل IPTV",
        subtitle: "StreamIP هو مشغل وسائط حديث لقوائم تشغيل IPTV الخاصة بك وخدمات البث المتوافقة. شاهد البث المباشر للقنوات التلفزيونية والأفلام والمسلسلات في واجهة نظيفة وسهلة الاستخدام مصممة للهواتف والأجهزة اللوحية وأجهزة Google TV.",
        description: "يدعم StreamIP تسجيل الدخول المتوافق مع الخادم وعناوين URL لقوائم تشغيل M3U، بما في ذلك تشغيل تدفقات HLS/M3U8 المتوافقة المقدمة من مصدر المحتوى الخاص بك. عندما يكون مدعومًا من مزود الخدمة الخاص بك، يمكن لتسجيل الدخول إلى الخادم توفير تنظيم محسن للقنوات التلفزيونية المباشرة والأفلام والمسلسلات التلفزيونية.",
        langSupport: "يتوفر StreamIP بـ 9 لغات: الإنجليزية والنرويجية والفرنسية والإسبانية والبرتغالية والعربية والألمانية والإيطالية والبولندية.",
        priceTag: "3.99 دولار فقط - شراء لمرة واحدة (بدون رسوم متكررة)",
        featuresTitle: "الميزات",
        importantTitle: "معلومات هامة",
        ctaBtn: "تحميل من Google Play",
        footerText: "أحضر المحتوى الخاص بك. ابدأ البث بطريقتك مع StreamIP.",
        features: [
            "تشغيل قنوات التلفزيon المباشرة من مصدر المحتوى الخاص بك",
            "تصفح الأفلام والمسلسلات التلفزيونية في فئات منظمة",
            "دعم تسجيل الدخول المتوافق مع الخادم وعناوين URL لقوائم تشغيل M3U",
            "دعم تشغيل تدفقات HLS/M3U8 المتوافقة",
            "دعم دليل البرامج الإلكتروني (EPG) عند توفره من مصدرك",
            "بث التدفقات المتوافقة إلى أجهزة Google Cast المدعومة",
            "فتح التدفقات في مشغل وسائط خارجي متوافق",
            "المفضلة للوصول السريع إلى المحتوى المفضل",
            "أقسام المشغلة مؤخرًا ومتابعة المشاهدة",
            "استئناف التشغيل للأفلام وحلقات التلفزيون",
            "خيارات تشغيل الحلقة التالية للمسلسلات المدعومة",
            "البحث والبحث في الفئات",
            "دعم الترجمة المصاحبة عند توفرها في البث",
            "دعم الهواتف والأجهزة اللوحية وأجهزة Google TV",
            "فرز المحتوى حسب المنطقة المفضلة (الشرق/الغرب)",
            "قفل تطبيق اختياري لمزيد من الخصوصية",
            "خيارات المظهر الفاتح والداكن"
        ],
        disclaimers: [
            "برنامج StreamIP هو مجرد مشغل وسائط فقط. لا يوفر التطبيق أو يبيع أو يتضمن أي قنوات تلفزيونية أو أفلام أو مسلسلات تلفزيونية أو قوائم تشغيل أو اشتراكات أو حسابات بث.",
            "لاستخدام التطبيق، يجب عليك إضافة قائمة التشغيل المتوافقة الخاصة بك أو تفاصيل الحساب من خدمة أو مصدر مصرح لك باستخدامه.",
            "أنت مسؤول عن ضمان حصولك على الحقوق والأذونات اللازمة للوصول إلى المحتوى المضاف إلى التطبيق وعرضه. لا ينتمي StreamIP إلى أي مزود محتوى ولا يعتمده أو يرتبط به.",
            "يعتمد المحتوى المتاح والفئات ومعلومات EPG والترجمات وجودة التشغيل وتوافق البث (Cast) وتوافق التدفق على مصدر المحتوى الخاص بك واتصال الإنترنت وميزات جهازك. يتطلب التشغيل الخارجي تثبيت تطبيق مشغل وسائط متوافق على جهازك."
        ]
    }
};
